
/*users table*/
create table public.users (
  user_id serial not null,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  email character varying(255) not null,
  phone character varying(20) null,
  password_hash character varying(255) not null,
  role character varying(50) not null default 'Patient'::character varying,
  address character varying(255) null,
  city character varying(100) null,
  country character varying(100) null default 'Pakistan'::character varying,
  constraint users_pkey primary key (user_id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;


/*suppliers table*/
create table public.suppliers (
  supplier_id bigint generated by default as identity not null,
  user_id bigint null,
  company_name character varying null,
  supplier_reg_id character varying null,
  constraint suppliers_pkey primary key (supplier_id),
  constraint fk_user foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;


/*pharmacists table*/
create table public.pharmacists (
  pharmacist_id bigint generated by default as identity not null,
  user_id bigint not null,
  pharmacy_name character varying(255) null,
  pharmacy_license character varying(255) null,
  constraint pharmacists_pkey primary key (pharmacist_id),
  constraint unique_pharmacist_user unique (user_id),
  constraint fk_pharmacist_user foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;


/*patients table*/
create table public.patients (
  patient_id bigint generated by default as identity not null,
  user_id integer not null,
  primary_doctor_id integer null,
  constraint patients_pkey primary key (patient_id),
  constraint patients_user_id_key unique (user_id),
  constraint fk_primary_doctor foreign KEY (primary_doctor_id) references users (user_id) on delete set null,
  constraint fk_user foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;


/*doctors table*/
create table public.doctors (
  doctor_id bigint generated by default as identity not null,
  user_id integer not null,
  specialty character varying(255) null,
  medical_license character varying(255) null,
  constraint doctors_pkey primary key (doctor_id),
  constraint unique_doctor_user unique (user_id),
  constraint fk_doctor_user foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;


/*medicines tables*/
create table public.medicines (
  medicine_id serial not null,
  supplier_id integer null,
  name character varying(255) null,
  category character varying(100) null,
  description text null,
  price numeric(10, 2) null,
  stock integer null,
  expiry_date date null,
  image_url character varying null,
  constraint medicines_pkey primary key (medicine_id),
  constraint fk_medicines_supplier foreign KEY (supplier_id) references users (user_id) on delete set null
) TABLESPACE pg_default;


/* card_items table*/
create table public.cart_items (
  cart_item_id serial not null,
  user_id integer null,
  medicine_id integer null,
  quantity integer not null default 1,
  added_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint cart_items_pkey primary key (cart_item_id),
  constraint cart_items_user_id_medicine_id_key unique (user_id, medicine_id),
  constraint cart_items_medicine_id_fkey foreign KEY (medicine_id) references medicines (medicine_id) on delete CASCADE,
  constraint cart_items_user_id_fkey foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;


/*prescriptions table*/
create table public.prescriptions (
  prescription_id serial not null,
  patient_id integer null,
  doctor_id integer null,
  date_issued date null,
  status character varying(50) null,
  prescription_image text null,
  notes text null,
  diagnosis text null,
  order_id integer null,
  constraint prescriptions_pkey primary key (prescription_id),
  constraint fk_prescription_order foreign KEY (order_id) references orders (order_id),
  constraint prescriptions_doctor_id_fkey foreign KEY (doctor_id) references users (user_id),
  constraint prescriptions_patient_id_fkey foreign KEY (patient_id) references users (user_id)
) TABLESPACE pg_default;

create index IF not exists idx_prescriptions_doctor on public.prescriptions using btree (doctor_id) TABLESPACE pg_default;

create index IF not exists idx_prescriptions_patient on public.prescriptions using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_prescriptions_order_id on public.prescriptions using btree (order_id) TABLESPACE pg_default;


/* orders table*/
create table public.orders (
  order_id serial not null,
  user_id integer null,
  prescription_id integer null,
  order_date timestamp without time zone null,
  total_price numeric(10, 2) null,
  status character varying(50) null,
  delivery_address text null,
  pharmacist_id integer null,
  cancellation_reason text null,
  tracking_info text null,
  constraint orders_pkey primary key (order_id),
  constraint orders_pharmacist_id_fkey foreign KEY (pharmacist_id) references users (user_id),
  constraint orders_prescription_id_fkey foreign KEY (prescription_id) references prescriptions (prescription_id),
  constraint orders_user_id_fkey foreign KEY (user_id) references users (user_id)
) TABLESPACE pg_default;


/* order_items table */
create table public.order_items (
  order_item_id serial not null,
  order_id integer null,
  medicine_id integer null,
  quantity integer not null,
  price numeric(10, 2) not null,
  constraint order_items_pkey primary key (order_item_id),
  constraint order_items_medicine_id_fkey foreign KEY (medicine_id) references medicines (medicine_id) on delete CASCADE,
  constraint order_items_order_id_fkey foreign KEY (order_id) references orders (order_id) on delete CASCADE
) TABLESPACE pg_default;


/*prescribed_medicines table*/
create table public.prescribed_medicines (
  prescribed_medicine_id serial not null,
  prescription_id integer null,
  medicine_id integer null,
  dosage character varying(100) null,
  frequency character varying(100) null,
  duration character varying(100) null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint prescribed_medicines_pkey primary key (prescribed_medicine_id),
  constraint prescribed_medicines_medicine_id_fkey foreign KEY (medicine_id) references medicines (medicine_id),
  constraint prescribed_medicines_prescription_id_fkey foreign KEY (prescription_id) references prescriptions (prescription_id) on delete CASCADE
) TABLESPACE pg_default;


/* supplier_inventory table*/
create table public.supplier_inventory (
  inventory_id serial not null,
  supplier_id integer null,
  medicine_id integer null,
  quantity_available integer not null,
  reorder_level integer null default 0,
  purchase_price numeric(10, 2) not null,
  selling_price numeric(10, 2) not null,
  expiry_date date null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint supplier_inventory_pkey primary key (inventory_id),
  constraint supplier_inventory_medicine_id_fkey foreign KEY (medicine_id) references medicines (medicine_id),
  constraint supplier_inventory_supplier_id_fkey foreign KEY (supplier_id) references suppliers (supplier_id)
) TABLESPACE pg_default;


/* stock_requests table*/
create table public.stock_requests (
  request_id serial not null,
  pharmacist_id integer not null,
  supplier_id integer not null,
  medicine_id integer not null,
  quantity_requested integer not null,
  notes text null,
  pharmacy_name character varying(255) null,
  request_date date not null default CURRENT_DATE,
  status character varying(50) not null default 'Pending'::character varying,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  rejection_reason text null,
  constraint stock_requests_pkey primary key (request_id),
  constraint stock_requests_medicine_id_fkey foreign KEY (medicine_id) references medicines (medicine_id) on delete CASCADE,
  constraint stock_requests_pharmacist_id_fkey foreign KEY (pharmacist_id) references users (user_id) on delete CASCADE,
  constraint stock_requests_supplier_id_fkey foreign KEY (supplier_id) references users (user_id) on delete CASCADE,
  constraint stock_requests_quantity_requested_check check ((quantity_requested > 0))
) TABLESPACE pg_default;

create index IF not exists idx_stock_requests_pharmacist on public.stock_requests using btree (pharmacist_id) TABLESPACE pg_default;

create index IF not exists idx_stock_requests_supplier on public.stock_requests using btree (supplier_id) TABLESPACE pg_default;

create index IF not exists idx_stock_requests_status on public.stock_requests using btree (status) TABLESPACE pg_default;

create index IF not exists idx_stock_requests_medicine on public.stock_requests using btree (medicine_id) TABLESPACE pg_default;


/*deliveries table*/
create table public.deliveries (
  delivery_id serial not null,
  request_id integer not null,
  delivery_status character varying(50) not null default 'NotShipped'::character varying,
  shipped_date date null,
  delivery_date date null,
  tracking_info text null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  constraint deliveries_pkey primary key (delivery_id),
  constraint deliveries_request_id_unique unique (request_id),
  constraint unique_request_id unique (request_id),
  constraint deliveries_request_id_fkey foreign KEY (request_id) references stock_requests (request_id) on delete CASCADE,
  constraint deliveries_delivery_status_check check (
    (
      (delivery_status)::text = any (
        (
          array[
            'NotShipped'::character varying,
            'Shipped'::character varying,
            'Delivered'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_deliveries_request on public.deliveries using btree (request_id) TABLESPACE pg_default;

create index IF not exists idx_deliveries_status on public.deliveries using btree (delivery_status) TABLESPACE pg_default;

create index IF not exists idx_deliveries_shipped_date on public.deliveries using btree (shipped_date) TABLESPACE pg_default;


/*payment table*/
create table public.payment (
  payment_id serial not null,
  order_id integer null,
  user_id integer null,
  date timestamp without time zone null default now(),
  amount numeric(10, 2) not null,
  method character varying(50) not null,
  card_last_four character varying(4) null,
  constraint payment_pkey primary key (payment_id),
  constraint payment_order_id_fkey foreign KEY (order_id) references orders (order_id),
  constraint payment_user_id_fkey foreign KEY (user_id) references users (user_id)
) TABLESPACE pg_default;